ARTIKEL = [
    {
        "id": "A01",
        "judul": "Cara Menjaga Kesehatan Paru-paru",
        "kategori": "Pencegahan",
        "ringkasan": "Panduan lengkap menjaga paru-paru tetap sehat dengan kebiasaan sederhana sehari-hari.",
        "gambar": "fa-lungs",
        "warna": "blue",
        "isi": [
            "Paru-paru adalah organ vital yang bekerja tanpa henti untuk menyuplai oksigen ke seluruh tubuh. Menjaga kesehatannya sangat penting untuk kualitas hidup yang baik.",
            "Hindari merokok dan paparan asap rokok. Rokok mengandung ribuan bahan kimia berbahaya yang merusak jaringan paru dan meningkatkan risiko kanker paru, bronkitis kronis, dan PPOK.",
            "Olahraga teratur seperti berjalan cepat, berenang, atau bersepeda selama 30 menit per hari dapat meningkatkan kapasitas paru dan sirkulasi oksigen.",
            "Konsumsi makanan kaya antioksidan seperti buah beri, apel, brokoli, dan teh hijau. Antioksidan membantu melindungi jaringan paru dari kerusakan radikal bebas.",
            "Jaga kualitas udara di dalam rumah dengan ventilasi yang baik, gunakan tanaman pembersih udara, dan bersihkan debu secara rutin.",
            "Lakukan vaksinasi sesuai jadwal, terutama vaksin influenza dan pneumonia, untuk mencegah infeksi saluran pernapasan.",
        ],
        "sumber": "WHO, Kemenkes RI 2025",
    },
    {
        "id": "A02",
        "judul": "Mengenal ISPA dan Cara Pencegahannya",
        "kategori": "Penyakit",
        "ringkasan": "Infeksi Saluran Pernapasan Akut (ISPA) adalah salah satu penyakit paling umum. Kenali gejala dan cara mencegahnya.",
        "gambar": "fa-head-side-mask",
        "warna": "cyan",
        "isi": [
            "ISPA adalah infeksi yang menyerang saluran pernapasan bagian atas maupun bawah. Penyebab utamanya adalah virus (Rhinovirus, Adenovirus) dan bakteri.",
            "Gejala ISPA meliputi batuk, pilek, demam ringan, sakit tenggorokan, dan bersin-bersin. Umumnya bersifat self-limiting dan sembuh dalam 5-7 hari.",
            "Penularan ISPA melalui droplet (percikan air liur) saat batuk atau bersin. Virus juga bisa menempel di permukaan benda dan bertahan beberapa jam.",
            "Cegah ISPA dengan mencuci tangan secara teratur, menggunakan masker di tempat ramai, menjaga daya tahan tubuh, dan menghindari kontak dengan orang sakit.",
            "Pengobatan ISPA bersifat simptomatis: istirahat cukup, perbanyak cairan hangat, dan konsumsi obat pereda gejala jika diperlukan. Antibiotik hanya efektif untuk infeksi bakteri.",
        ],
        "sumber": "Kemenkes RI, CDC 2025",
    },
    {
        "id": "A03",
        "judul": "Flu Biasa vs COVID-19: Apa Bedanya?",
        "kategori": "Perbandingan",
        "ringkasan": "Memahami perbedaan gejala antara influenza biasa dan COVID-19 untuk penanganan yang tepat.",
        "gambar": "fa-shield-virus",
        "warna": "rose",
        "isi": [
            "Influenza (flu) dan COVID-19 sama-sama disebabkan oleh virus pernapasan dan memiliki gejala yang mirip. Namun ada beberapa perbedaan kunci.",
            "Gejala khas COVID-19 yang jarang ditemui pada flu biasa adalah hilangnya indra penciuman (anosmia) dan perasa (ageusia). Ini terjadi karena virus menyerang sel saraf olfaktori.",
            "Masa inkubasi flu biasanya 1-4 hari, sedangkan COVID-19 bisa 2-14 hari. Ini membuat tracing kontak COVID-19 lebih sulit.",
            "Demam pada flu biasanya muncul tiba-tiba dengan suhu tinggi, sementara COVID-19 bisa dimulai dengan demam ringan yang meningkat perlahan.",
            "Keduanya bisa menyebabkan komplikasi serius pada kelompok rentan. Vaksinasi adalah perlindungan terbaik untuk kedua penyakit ini.",
            "Tes PCR atau antigen diperlukan untuk diagnosis pasti. Jika ragu, lakukan isolasi mandiri dan konsultasi dengan tenaga medis.",
        ],
        "sumber": "WHO, CDC 2025",
    },
    {
        "id": "A04",
        "judul": "Bahaya Merokok bagi Sistem Pernapasan",
        "kategori": "Pencegahan",
        "ringkasan": "Rokok adalah musuh utama paru-paru. Berikut dampak buruknya pada kesehatan pernapasan Anda.",
        "gambar": "fa-smoking-ban",
        "warna": "amber",
        "isi": [
            "Setiap batang rokok mengandung lebih dari 7.000 bahan kimia, dimana 70 di antaranya bersifat karsinogenik (penyebab kanker).",
            "Asap rokok merusak silia (rambut halus) di saluran pernapasan yang berfungsi menyaring kotoran. Akibatnya, kuman dan partikel berbahaya mudah masuk ke paru.",
            "Perokok aktif memiliki risiko 15-30 kali lebih tinggi terkena kanker paru dibanding non-perokok. Rokok juga menyebabkan PPOK (Penyakit Paru Obstruktif Kronis).",
            "Merokok juga memperburuk kondisi asma, bronkitis, dan pneumonia. Proses penyembuhan infeksi pernapasan pada perokok lebih lambat.",
            "Berhenti merokok memberikan manfaat yang signifikan: setelah 2 minggu sirkulasi darah membaik, setelah 1 tahun risiko penyakit jantung turun 50%.",
        ],
        "sumber": "CDC, Kemenkes RI 2025",
    },
    {
        "id": "A05",
        "judul": "Tips Menjaga Kualitas Udara di Dalam Rumah",
        "kategori": "Gaya Hidup",
        "ringkasan": "Udara bersih di rumah sangat penting untuk kesehatan pernapasan keluarga Anda.",
        "gambar": "fa-wind",
        "warna": "emerald",
        "isi": [
            "Udara dalam ruangan bisa 2-5 kali lebih tercemar dibanding udara luar, terutama jika ventilasi buruk.",
            "Buka jendela setiap pagi selama 10-15 menit untuk sirkulasi udara. Udara segar membantu mengurangi konsentrasi polutan dalam ruangan.",
            "Gunakan tanaman pembersih udara alami seperti Lidah Mertua (Sansevieria), Palem Bambu, atau Sirih Gading. Tanaman ini mampu menyerap polutan dan melepaskan oksigen.",
            "Bersihkan debu secara rutin dengan kain microfiber basah (jangan kering, karena menyebarkan debu). Gunakan vacuum cleaner dengan filter HEPA.",
            "Hindari penggunaan pengharum ruangan kimiawi berlebihan. Sebagai alternatif, gunakan essential oil alami seperti peppermint atau lavender.",
            "Pasang exhaust fan di dapur dan kamar mandi untuk mengeluarkan asap masak dan uap air berlebih yang bisa menyebabkan pertumbuhan jamur.",
        ],
        "sumber": "EPA, Kemenkes RI 2025",
    },
    {
        "id": "A06",
        "judul": "Olahraga Pernapasan untuk Paru-paru Sehat",
        "kategori": "Gaya Hidup",
        "ringkasan": "Latihan pernapasan sederhana yang bisa dilakukan di rumah untuk memperkuat paru-paru.",
        "gambar": "fa-heartbeat",
        "warna": "indigo",
        "isi": [
            "Olahraga pernapasan membantu meningkatkan kapasitas paru, mengurangi stres, dan memperbaiki kualitas tidur. Cocok untuk semua usia.",
            "Teknik Pernapasan Diafragma: Duduk tegak, letakkan satu tangan di perut. Tarik napas dalam melalui hidung selama 4 detik hingga perut mengembang. Tahan 4 detik, lalu hembuskan perlahan melalui mulut selama 6 detik.",
            "Teknik Pursed-Lip Breathing: Tarik napas melalui hidung selama 2 detik. Kerutkan bibir seolah hendak bersiul, lalu hembuskan napas perlahan selama 4-6 detik. Teknik ini membantu menjaga saluran napas tetap terbuka lebih lama.",
            "Latihan 4-7-8: Tarik napas 4 detik, tahan 7 detik, hembuskan 8 detik. Lakukan 4-8 siklus. Teknik ini sangat efektif untuk menenangkan sistem saraf.",
            "Lakukan latihan pernapasan 2-3 kali sehari, masing-masing 5-10 menit. Konsistensi lebih penting daripada durasi.",
        ],
        "sumber": "American Lung Association 2025",
    },
    {
        "id": "A07",
        "judul": "Kapan Harus ke Dokter untuk Masalah Pernapasan?",
        "kategori": "Panduan",
        "ringkasan": "Panduan mengenali tanda-tanda bahaya pada sistem pernapasan yang memerlukan penanganan medis segera.",
        "gambar": "fa-ambulance",
        "warna": "rose",
        "isi": [
            "Tidak semua keluhan pernapasan memerlukan kunjungan ke dokter. Namun ada beberapa tanda bahaya yang tidak boleh diabaikan.",
            "Segera ke IGD jika mengalami: sesak napas berat yang muncul tiba-tiba, bibir atau ujung jari kebiruan (sianosis), nyeri dada hebat, atau batuk darah dalam jumlah banyak.",
            "Konsultasi ke dokter umum jika: demam tinggi lebih dari 3 hari, batuk berdahak kuning/hijau kental, batuk lebih dari 2 minggu, atau sesak napas ringan saat aktivitas.",
            "Pemeriksaan penunjang yang mungkin disarankan dokter: rontgen dada, tes darah lengkap, tes dahak (kultur), atau spirometri (tes fungsi paru).",
            "Jika memiliki penyakit penyerta (asma, diabetes, jantung, atau imunitas lemah), sebaiknya lebih proaktif dalam memeriksakan keluhan pernapasan.",
        ],
        "sumber": "Kemenkes RI, WHO 2025",
    },
    {
        "id": "A08",
        "judul": "Nutrisi untuk Kesehatan Paru-paru",
        "kategori": "Gaya Hidup",
        "ringkasan": "Makanan dan nutrisi yang membantu menjaga fungsi paru-paru optimal.",
        "gambar": "fa-apple-alt",
        "warna": "emerald",
        "isi": [
            "Pola makan sehat berperan penting dalam menjaga kesehatan paru-paru dan mengurangi risiko infeksi saluran pernapasan.",
            "Vitamin C (jeruk, kiwi, paprika merah) memperkuat sistem imun dan membantu melawan infeksi pernapasan. Konsumsi 75-90 mg per hari.",
            "Vitamin D (ikan berlemak, telur, sinar matahari) penting untuk fungsi imun. Kekurangan vitamin D dikaitkan dengan risiko infeksi pernapasan yang lebih tinggi.",
            "Omega-3 (ikan salmon, sarden, kacang kenari) memiliki efek anti-inflamasi yang membantu mengurangi peradangan saluran pernapasan.",
            "Antioksidan seperti flavonoid (apel, teh hijau, bawang) dan beta-karoten (wortel, ubi jalar) melindungi jaringan paru dari kerusakan oksidatif.",
            "Hindari makanan yang memicu peradangan seperti gorengan, makanan olahan, dan gula berlebih. Perbanyak konsumsi sayuran hijau dan buah segar.",
        ],
        "sumber": "American Lung Association, WHO 2025",
    },
]
